req-helpers:
  authorization: 
  client-id: 
  client-secret: 
  accept: application/json
  endpoints:
    patient: 
    patient-problems: 
    patient-lab-results: 
    patient-vital-signs: 
    patient-encounters: 